#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/_core/main"

##? Compress audio
##?
##? Usage:
##?   audio --input=<input> [--output=<output>]
##?
##? Options:
##?   -h --help             Show screen.
##?   -i --input <input>     Input file.
##?   -o --output <output>   Output file.
##?
##? Example:
##?   audio --input input.mp3 --output output.mp3
docs::parse "$@"

if [[ -z "$output" ]]; then
	input_path=$(dirname "$input")
	input_name=$(basename "$input" | sed 's/\.[^.]*$//')
	input_format=$(basename "$input" | sed -n 's/.*\.\([^\.]*\)$/\1/p')

	output="${input_path}/${input_name}-compressed"

	if [[ -n "$input_format" ]]; then
		output="${output}.${input_format}"
	fi
fi

ffmpeg -i "$input" -codec:a libmp3lame -b:a 192k "$output"
