#!/bin/bash

alias ai="ask_ai"

list_gemini_models(){
	echo "gemini-2.5-pro (pro)(slow)"
	echo "gemini-2.5-flash (flash)(normal)(default)"
	echo "gemini-2.5-flash-lite (lite)(fast)"
}

list_bedrock_models(){
	echo "sonnet (sonnet)(normal)(slow)(default)"
	echo "haiku (haiku)(fast)"
}

ask_bedrock() {
	declare -A models

	models[haiku]="us.anthropic.claude-haiku-4-5-20251001-v1:0"
	models[sonnet]="us.anthropic.claude-sonnet-4-5-20250929-v1:0"
	
	models[fast]="${models[haiku]}"
	models[normal]="${models[sonnet]}"
	models[slow]="${models[sonnet]}"
	
	models[default]="${models[sonnet]}"

	local prompt_text="$1"
	local modelArgument="$2"
	local model="${models[default]}"

	if [[ -n "$modelArgument" ]]; then
    	if [[ -v 'models[$modelArgument]' ]]; then
        	model="${models[$modelArgument]}"
    	else
        	model="$modelArgument"
    	fi
	fi

	local response_path=$(mktemp ${TMPDIR}XXXXXXXXXX)
	local message=$(jq -n --arg prompt_text "$prompt_text" \
		'{
			"max_tokens": 130000,
			"anthropic_version": "bedrock-2023-05-31",
            "messages": [{
				"role": "user",
				"content": ($prompt_text)
			}]
          }')

	aws bedrock-runtime invoke-model \
		--profile cline-profile \
		--model-id "$model" \
		--body "$message" \
		--cli-binary-format raw-in-base64-out \
		--no-cli-pager \
		"$response_path" >/dev/null

	cat "$response_path" | jq -r '.content[0].text'
	rm -f "$response_path" 2>/dev/null
}

can_ask_gemini() {
	if [ -z "$GEMINI_API_KEY" ]; then
		return $FALSE
	fi

	return $TRUE
}

ask_gemini() {
	declare -A models
	
	models[lite]="gemini-2.5-flash-lite"
	models[flash]="gemini-2.5-flash"
	models[pro]="gemini-2.5-pro"

	models[fast]="${models[lite]}"
	models[normal]="${models[flash]}"
	models[slow]="${models[pro]}"

	models[default]="${models[flash]}"

	local prompt_text="$1"
	local modelArgument="$2"
	local model="${models[default]}"

	if [[ -n "$modelArgument" ]]; then
    	if [[ -v 'models[$modelArgument]' ]]; then
        	model="${models[$modelArgument]}"
    	else
        	model="$modelArgument"
    	fi
	fi

	if [ -n "$GEMINI_API_KEY" ]; then
		local message=$(jq -n --arg prompt_text "$prompt_text" \
			'{
            "contents": [{
              "parts": [{
                "text": ($prompt_text)
              }]
            }]
          }')

		local response=$(curl -s "https://generativelanguage.googleapis.com/v1/models/${model}:generateContent?key=$GEMINI_API_KEY" \
			-H 'Content-Type: application/json' \
			-X POST \
			-d "$message")

		suggestions=$(printf '%s' "$response" | jq -R -s 'fromjson? | .candidates[0].content.parts[0].text // empty')

		if [ -n "$suggestions" ]; then
			printf '%s' "$suggestions" | jq -r '.'
		else
			echo "Error: Failed to get suggestions from Gemini"

			if [ -n "$response" ]; then
				echo "$response"
			fi

			return 1
		fi
	else
		system::print_error "GEMINI_API_KEY environment variable is not set"
		return 1
	fi
}

ask_ai() {
	if can_ask_gemini; then
		ask_gemini "$*"
		return $?
	fi

	ask_bedrock "$*"
}