#!/bin/bash

alias ai="ask_ai"

list_gemini_models(){
	echo "gemini-2.5-pro (pro)(slow)"
	echo "gemini-2.5-flash (flash)(normal)(default)"
	echo "gemini-2.5-flash-lite (lite)(fast)"
}

list_bedrock_models(){
	echo "sonnet (sonnet)(normal)(slow)(default)"
	echo "haiku (haiku)(fast)"
}

_get_bedrock_model() {
    case "$1" in
        haiku)   echo "us.anthropic.claude-haiku-4-5-20251001-v1:0" ;;
        sonnet)  echo "us.anthropic.claude-sonnet-4-5-20250929-v1:0" ;;
        fast)    _get_bedrock_model "haiku" ;;
        normal)  _get_bedrock_model "sonnet" ;;
        slow)    _get_bedrock_model "sonnet" ;;
        default) _get_bedrock_model "sonnet" ;;
        *)       echo "$1" ;;  # Unknown key
    esac
}

_get_gemini_model() {
    case "$1" in
        lite)   echo "gemini-2.5-flash-lite" ;;
        flash)  echo "gemini-2.5-flash" ;;
		pro)  echo "gemini-2.5-pro" ;;
        fast)    _get_bedrock_model "lite" ;;
        normal)  _get_bedrock_model "flash" ;;
        slow)    _get_bedrock_model "pro" ;;
        default) _get_bedrock_model "flash" ;;
        *)       echo "$1" ;;  # Unknown key
    esac
}

ask_bedrock() {
	local prompt_text="$1"
	local modelArgument="$2"
	local model=$(_get_bedrock_model "default")

	if [[ -n "$modelArgument" ]]; then
    	model=$(_get_bedrock_model "$modelArgument")
	fi

	local response_path=$(mktemp ${TMPDIR}XXXXXXXXXX)
	local message=$(jq -n --arg prompt_text "$prompt_text" \
		'{
			"max_tokens": 130000,
			"anthropic_version": "bedrock-2023-05-31",
            "messages": [{
				"role": "user",
				"content": ($prompt_text)
			}]
          }')

	aws bedrock-runtime invoke-model \
		--profile cline-profile \
		--model-id "$model" \
		--body "$message" \
		--cli-binary-format raw-in-base64-out \
		--no-cli-pager \
		"$response_path" >/dev/null

	cat "$response_path" | jq -r '.content[0].text'
	rm -f "$response_path" 2>/dev/null
}

can_ask_gemini() {
	if [ -z "$GEMINI_API_KEY" ]; then
		return $FALSE
	fi

	return $TRUE
}

ask_gemini() {
	local prompt_text="$1"
	local modelArgument="$2"
	local model=$(_get_gemini_model "default")

	if [[ -n "$modelArgument" ]]; then
    	model=$(_get_gemini_model "$modelArgument")
	fi

	if [ -n "$GEMINI_API_KEY" ]; then
		local message=$(jq -n --arg prompt_text "$prompt_text" \
			'{
            "contents": [{
              "parts": [{
                "text": ($prompt_text)
              }]
            }]
          }')

		local response=$(curl -s "https://generativelanguage.googleapis.com/v1/models/${model}:generateContent?key=$GEMINI_API_KEY" \
			-H 'Content-Type: application/json' \
			-X POST \
			-d "$message")

		suggestions=$(printf '%s' "$response" | jq -R -s 'fromjson? | .candidates[0].content.parts[0].text // empty')

		if [ -n "$suggestions" ]; then
			printf '%s' "$suggestions" | jq -r '.'
		else
			echo "Error: Failed to get suggestions from Gemini"

			if [ -n "$response" ]; then
				echo "$response"
			fi

			return 1
		fi
	else
		system::print_error "GEMINI_API_KEY environment variable is not set"
		return 1
	fi
}

ask_ai() {
	if can_ask_gemini; then
		ask_gemini "$1" "$2"
	else
		ask_bedrock "$1" "$2"
	fi
}