#!/bin/bash

# DOCKER
alias dpsa='docker ps -a'
alias dsac='docker stop $(docker ps -a -q)'
alias drac='docker rm $(docker ps -a -q)'
alias drai='docker rmi $(docker images -a -q)'
alias di='docker images'
alias dpsn='docker ps --format "{{.Names}}"'

dsc() {     _fzf_select -m -j -p "Stop container(s): "          "docker stop <attr>"             "docker ps --format '{{.Names}}'"                       "$@"; }
drc() {     _fzf_select -m -j -p "Remove container(s): "        "docker rm <attr>"               "docker ps -a --format '{{.Names}}'"                    "$@"; }
dl()  {     _fzf_select       -p "Container logs: "             "docker logs <attr>"             "docker ps --format '{{.Names}}'"                       "$@"; }
dlf() {     _fzf_select       -p "Container logs (follow): "    "docker logs -f <attr>"          "docker ps --format '{{.Names}}'"                       "$@"; }
dri() {     _fzf_select -m -j -p "Remove image(s): "            "docker rmi <attr>"              "docker images --format '{{.Repository}}:{{.Tag}}'"     "$@"; }
debash() {  _fzf_select       -p "Exec bash: "                  "docker exec -it <attr> bash"    "docker ps --format '{{.Names}}'"                       "$@"; }
desh() {    _fzf_select       -p "Exec sh: "                    "docker exec -it <attr> sh"      "docker ps --format '{{.Names}}'"                       "$@"; }
dezsh() {   _fzf_select       -p "Exec zsh: "                   "docker exec -it <attr> zsh"     "docker ps --format '{{.Names}}'"                       "$@"; }
de() {      _fzf_select       -p "Exec: "                       "docker exec -it <attr>"         "docker ps --format '{{.Names}}'"                       "$@"; }

# DOCKER COMPOSE
alias dcu='docker-compose up -d'     			# up
alias dcs='docker-compose stop'      			# stop
alias dcb='docker-compose build'     			# build
alias dcbn='docker-compose build --no-cache'    # build --no-cache
alias dcbu='dcb && sleep 1 && dcu'   			# build & up
alias dcbnu='dcbn && sleep 1 && dcu'   			# build --no-cache & up
alias dcsbu='dcs && sleep 1 && dcbu' 			# stop, build & up
alias dcsbnu='dcs && sleep 1 && dcbnu' 			# stop, build --no-cache & up
alias dcr='dcs && sleep 1 && dcu'    			# restart => stop & up

# Argument: container name & shell type (bash by default)
# docker-compose up & exec container
dcue() {
    dcu
    de "$@"
}
