#!/bin/bash

alias tf="terraform"
alias tfp="terraform plan"
alias tfa="terraform apply"
alias tfinit="terraform init"
alias tfo="terraform output"
alias tfs="terraform show"
alias tfc="terraform console"
alias tff="terraform fmt"
alias tfd='confirm_action "terraform destroy" "Are you sure you want to destroy the current state?"'
