#!/bin/bash

set -e

export DOTFILES_PATH="$HOME/.dotfiles"
export DOTFILES_PRIVATE_PATH="$DOTFILES_PATH/private/dotfiles"

source "$DOTFILES_PATH/shell/.shellrc"
source "$DOTFILES_PATH/installation/install_utils"

confirm_verbose
select_installation_type

system::update
system::upgrade

mkdir -p "$DOTFILES_PATH/private"
install_private_dotfiles
install_raycast_extension

load_linux_repositories
system::update true

install_packages
set_zsh_shell

source "$DOTFILES_PATH/installation/install_references"
