#!/bin/bash

source "$DOTFILES_PATH/scripts/_core/main"

for script in "$DOTFILES_PATH"/scripts/*; do
    if [[ -f "$script" && "$script" != "$DOTFILES_PATH/scripts/_main" ]]; then
        source "$script"
    fi
done
