#!/bin/bash

source "$DOTFILES_PATH/scripts/_core/main"
source "$DOTFILES_PATH/shell/aliases/ai"

##? Downloads a video audio in the current directory
##?
##? Usage:
##?   ask <question>...
docs::parse "$@"

ask_ai "$*"